<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Nallans-NewPC" name="com.JusDone.qa.TestCases.AcctPageTest" tests="8" failures="1" timestamp="22 Jan 2018 19:22:13 GMT" time="145.538" errors="0">
  <testcase name="verifyingCorrectAcctPageTest" time="12.689" classname="com.JusDone.qa.TestCases.AcctPageTest">
    <failure type="java.lang.AssertionError" message="expected [p
p21] but found [S
Signup]">
      <![CDATA[java.lang.AssertionError: expected [p
p21] but found [S
Signup]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.JusDone.qa.Pages.AcctPage.verifyingCorrectAcctPage(AcctPage.java:36)
	at com.JusDone.qa.TestCases.AcctPageTest.verifyingCorrectAcctPageTest(AcctPageTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyingCorrectAcctPageTest -->
  <testcase name="VerifyingErrorPageTest" time="33.374" classname="com.JusDone.qa.TestCases.AcctPageTest"/>
  <testcase name="verifyNameLogoTest" time="13.759" classname="com.JusDone.qa.TestCases.AcctPageTest"/>
  <testcase name="verifyLogOutLogoTest" time="13.601" classname="com.JusDone.qa.TestCases.AcctPageTest"/>
  <testcase name="verifySignupLogo" time="14.805" classname="com.JusDone.qa.TestCases.AcctPageTest"/>
  <testcase name="ClickNameBtnTest" time="13.612" classname="com.JusDone.qa.TestCases.AcctPageTest"/>
  <testcase name="ClickLogOutBtnTest" time="31.788" classname="com.JusDone.qa.TestCases.AcctPageTest"/>
  <testcase name="ClickJDLogoTest" time="11.910" classname="com.JusDone.qa.TestCases.AcctPageTest"/>
</testsuite> <!-- com.JusDone.qa.TestCases.AcctPageTest -->
